name: build

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: check out code
      uses: actions/checkout@v3
    - name: build code
      run: go build -v ./...
    - name: test code
      run: go test -race -v ./...
    - name: print job status
      run: echo "Job status was ${{ job.status }}."